import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

export const addPhrase = mutation({
  handler: async (ctx) => {
    const mockedPhrases = [
      "Que la fuerza ilumine tu camino ahora y siempre joven aprendiz",
      "Voy a hacerle una oferta imposible de rechazar cuando caiga la noche",
      "Nuestro planeta necesita héroes azules listos para conectarse con los espíritus",
      "Algunos hombres solo quieren ver el mundo arder en caos total",
      "No hay lugar como el hogar aun cuando brille un mágico camino amarillo",
      "La vida se abre paso incluso en un parque lleno de dinosaurios hambrientos",
      "Corre Forrest corre que las zapatillas pueden llevarte hasta el horizonte",
      "Volveré después de equiparme con más acero y gafas oscuras",
      "Soy inevitable pero aun así alguien podría intentar chasquear mis planes",
      "En este juego de tronos quien se incline acabará perdiendo la cabeza",
      "No pronuncies su nombre tres veces o despertarás caos en la sala",
      "La primera regla sobre este lugar secreto es jamás hablar sobre él",
      "Mantén cerca a tus amigos pero más cerca todavía a tus enemigos",
      "¡Wingardium leviosa amigos míos no vamos a quedarnos pegados al suelo!",
      "Necesitamos una velocidad de ochenta y ocho millas para regresar a casa",
      "Mi casa teléfono necesito contactar antes de desaparecer entre las estrellas",
      "Nunca dejaré que te vayas prometo que mi corazón continuará latiendo",
      "Hay cuchara inexistente porque la realidad puede doblarse dentro de la mente",
      "Di qué otra vez y comprobarás lo inesperado en esta conversación amistosa",
      "Ojo del tigre sonando venceremos a cualquier rival sobre el cuadrilátero",
      "En el espacio nadie escucha tus gritos mientras te acecha la oscuridad",
      "He visto cosas que vosotros no creeríais brillando más allá del cinturón",
      "Un anillo para gobernarlos a todos y perderse en sombras ardientes",
      "¿Por qué está siempre enterrado el tesoro donde nadie piensa buscar primero?",
      "Hasta el infinito y más allá juguete valiente demuestra tu coraje",
      "Un gran poder exige una responsabilidad incluso mayor recuerda cuidadoso héroe arácnido",
      "Los ogros son como cebollas poseen muchas capas bajo su piel",
      "Sigue nadando sigue nadando nunca dejes que la corriente te derrote",
      "Señorita vamos a convertirnos en hombres quien traerá honor a nuestra familia",
      "Hakuna matata olvida preocupaciones vive feliz sin mirar problemas pasados",
      "Descongélalo con amor verdadero cuando el invierno acecha tu reino helado de cristal",
      "Hasta medianoche todo cambiará asegúrate de regresar antes del último campanazo",
      "Atrápalos todos pues es el destino de todo entrenador valiente y curioso",
      "Es peligroso salir solo toma esta espada antes de iniciar tu aventura",
      "¡Mamma mia vamos a rescatar a la princesa del villano bigotudo saltando!",
      "Corre tan rápido como el viento azul que atraviesa colinas mecánicas",
      "Hadouken desata tu energía interior para vencer al rival frente a ti",
      "Termina este combate con un fatality impecable y conquista la torre",
      "Jefe maestro despierta necesitamos salvar la humanidad del gran pacto alienígena",
      "Mantente en la zona escucha los pasos enemigos antes que te rodeen",
      "Construye rápido protege tu fuerte antes de que la tormenta te devore",
      "Destruye el nexo enemigo trabajando en equipo con habilidades perfectamente coordinadas",
      "Por la Horda grita mientras marchas contra la Alianza en tierras devastadas",
      "Pica bloque coloca antorchas evita caer en lava fundida durante la minería",
      "Roba un auto conduce por la ciudad y evita atraer demasiada atención",
      "Ensilla tu caballo cabalga hacia el atardecer en busca de redención",
      "Cuando todo colapse mantén cerca a esa niña porque representa la esperanza",
      "Desata la furia del espartano para desafiar a los mismísimos dioses",
      "No hay tesoro imposible si tienes cuerdas desequipadas y un mapa viejo",
      "Tómate tu tiempo roba corazones mientras cambias la corrupción de la sociedad",
      "El mundo necesita héroes variados con habilidades únicas que cooperen para victorias épicas",
      "La tarta es mentira mantén la calma y continúa probando con portales",
      "Prepárate para consecuencias imprevistas al aceptar ese trabajo peligroso bajo tierra",
      "Las ciudades bajo el mar albergan secretos terribles y sueños de grandeza",
      "Comandante el destino de la galaxia depende de tus decisiones morales cruciales",
      "Un meteorito de impacto reunirá materias y sueños protejamos nuestro planeta",
      "Sólido o líquido el sigilo es tu mayor arma contra caminantes patrullando",
      "La niebla devora la ciudad acompañada de sirenas que advierten horrores cercanos",
      "Destruye demonios con tu escopeta mientras un riff pesado retumba sin descanso",
      "El virus se propagó abre la puerta solo si confías totalmente en sobrevivientes",
      "Come todas las píldoras evita fantasmas hambrientos en laberintos infinitos de neón",
      "Gira piezas rápidamente para llenar líneas completas antes del inevitable bloqueo",
      "Libra combates multitudinarios lanzando personajes contra escenarios llenos de caos",
      "Un corazón conecta mundos Disney mientras compañeros luchan con llaves luminosas gigantes",
      "Hay un impostor entre nosotros completando tareas es tu única esperanza",
      "Alza tu espada ancestral desafiando a dioses olvidados en tierras destrozadas",
      "Las calles brillan con neón y ciberimplantes modifican cada susurro humano",
      "El miedo es el asesino de la mente recuerda tu mantra sobre la arena",
      "Esto pertenece en un museo aunque las trampas antiguas no quieran permitirlo",
      "Yippee ki yay celebra la navidad saltando desde rascacielos bajo fuego cruzado",
      "Tus misiones autodestructivas terminarán en cinco segundos si aceptas el desafío",
      "El agente con licencia para matar siempre prefiere su martini agitado sin hielo",
      "Venganza vestida de amarillo empuña la katana para ajustar cuentas sangrientas",
      "La esperanza es algo bueno quizá lo mejor y nunca muere en prisión",
      "Lo que hacemos en la vida resuena por toda la eternidad guerrero romano",
      "Esta es esparta grita mientras derribas al mensajero en la fosa",
      "Pueden quitarnos la vida pero jamás arrebatarán nuestra ansiada libertad",
      "Di hola a mi pequeño amigo antes de que todo explote a disparos",
      "Necesito velocidad sentir la adrenalina antes de volar sobre los cazas",
      "¿A quién vas a llamar cuando los fantasmas inunden la ciudad?",
      "Necesitarás un barco más grande para enfrentar lo que acecha bajo el agua",
      "Quedarse solo en casa significa preparar trampas geniales contra ladrones inútiles",
      "Pasamos juntos el desayuno y descubrimos que dentro somos todos bastante notables",
      "El miércoles todos visten rosa si quieres pertenecer al grupo ganador",
      "La vida se mueve rápido mejor tomas un descanso antes de perderla",
      "Aquí está Johnny anunciando terror tras una puerta destrozada a hachazos",
      "Un motel solitario puede esconder a un diablo con sonrisa maternal",
      "El silencio de los corderos viene con un Chianti y habas otoñales",
      "Siete pecados marcarán el final de un juego macabro con cajas",
      "La sospecha usual recae siempre en el individuo menos evidente del grupo",
      "Debes ir más profundo en el sueño para plantar una simple idea",
      "El amor traspasa agujeros negros y códigos Morse a través del tiempo",
      "Hasta la vista bebé dijo mientras congelaba su enemigo con nitrógeno líquido",
      "Furia en la carretera impulsa guerreros supervivientes por desolados páramos incendiados",
      "Vivir rápido y furioso significa familia primero acelerador después y frenos nunca",
      "John se tomó un mal día personal y nadie quedó en pie",
      "La grasa es el camino armonizando artes marciales con sabiduría empapada en tallarines",
      "Es tan esponjoso como para conquistar corazones con su risa villanesca",
      "Banana grita la tropa amarilla causando caos adorable con travesuras desmedidas",
      "La aventura comienza con globos llevándote a explorar cataratas perdidas y recuerdos",
    ];

    const insertPromises = mockedPhrases.map((phrase) =>
      ctx.db.insert("phrase", {
        text: phrase,
        language: "es",
      })
    );

    const results = await Promise.all(insertPromises);

    return results;
  },
});

export const getPhrases = query({
  handler: async (ctx, args) => {
    // Get all phrases from the database
    return await ctx.db.query("phrase").collect();
  },
});
