export const typingContentSeed = {
  practicePhrases: [
  "Que la fuerza ilumine tu camino ahora y siempre joven aprendiz",
  "Voy a hacerle una oferta imposible de rechazar cuando caiga la noche",
  "Nuestro planeta necesita héroes azules listos para conectarse con los espíritus",
  "Algunos hombres solo quieren ver el mundo arder en caos total",
  "No hay lugar como el hogar aun cuando brille un mágico camino amarillo",
  "La vida se abre paso incluso en un parque lleno de dinosaurios hambrientos",
  "Corre Forrest corre que las zapatillas pueden llevarte hasta el horizonte",
  "Volveré después de equiparme con más acero y gafas oscuras",
  "Soy inevitable pero aun así alguien podría intentar chasquear mis planes",
  "En este juego de tronos quien se incline acabará perdiendo la cabeza",
  "No pronuncies su nombre tres veces o despertarás caos en la sala",
  "La primera regla sobre este lugar secreto es jamás hablar sobre él",
  "Mantén cerca a tus amigos pero más cerca todavía a tus enemigos",
  "Wingardium leviosa amigos míos no vamos a quedarnos pegados al suelo!",
  "Necesitamos una velocidad de ochenta y ocho millas para regresar a casa",
  "Mi casa teléfono necesito contactar antes de desaparecer entre las estrellas",
  "Nunca dejaré que te vayas prometo que mi corazón continuará latiendo",
  "Hay cuchara inexistente porque la realidad puede doblarse dentro de la mente",
  "Di qué otra vez y comprobarás lo inesperado en esta conversación amistosa",
  "Ojo del tigre sonando venceremos a cualquier rival sobre el cuadrilátero",
  "En el espacio nadie escucha tus gritos mientras te acecha la oscuridad",
  "He visto cosas que vosotros no creeríais brillando más allá del cinturón",
  "Un anillo para gobernarlos a todos y perderse en sombras ardientes",
  "¿Por qué está siempre enterrado el tesoro donde nadie piensa buscar primero?",
  "Hasta el infinito y más allá juguete valiente demuestra tu coraje",
  "Un gran poder exige una responsabilidad incluso mayor recuerda cuidadoso héroe arácnido",
  "Los ogros son como cebollas poseen muchas capas bajo su piel",
  "Sigue nadando sigue nadando nunca dejes que la corriente te derrote",
  "Señorita vamos a convertirnos en hombres quien traerá honor a nuestra familia",
  "Hakuna matata olvida preocupaciones vive feliz sin mirar problemas pasados",
  "Descongélalo con amor verdadero cuando el invierno acecha tu reino helado de cristal",
  "Hasta medianoche todo cambiará asegúrate de regresar antes del último campanazo",
  "Atrápalos todos pues es el destino de todo entrenador valiente y curioso",
  "Es peligroso salir solo toma esta espada antes de iniciar tu aventura",
  "Mamma mia vamos a rescatar a la princesa del villano bigotudo saltando!",
  "Corre tan rápido como el viento azul que atraviesa colinas mecánicas",
  "Hadouken desata tu energía interior para vencer al rival frente a ti",
  "Termina este combate con un fatality impecable y conquista la torre",
  "Jefe maestro despierta necesitamos salvar la humanidad del gran pacto alienígena",
  "Mantente en la zona escucha los pasos enemigos antes que te rodeen",
  "Construye rápido protege tu fuerte antes de que la tormenta te devore",
  "Destruye el nexo enemigo trabajando en equipo con habilidades perfectamente coordinadas",
  "Por la Horda grita mientras marchas contra la Alianza en tierras devastadas",
  "Pica bloque coloca antorchas evita caer en lava fundida durante la minería",
  "Roba un auto conduce por la ciudad y evita atraer demasiada atención",
  "Ensilla tu caballo cabalga hacia el atardecer en busca de redención",
  "Cuando todo colapse mantén cerca a esa niña porque representa la esperanza",
  "Desata la furia del espartano para desafiar a los mismísimos dioses",
  "No hay tesoro imposible si tienes cuerdas desequipadas y un mapa viejo",
  "Tómate tu tiempo roba corazones mientras cambias la corrupción de la sociedad",
  "El mundo necesita héroes variados con habilidades únicas que cooperen para victorias épicas",
  "La tarta es mentira mantén la calma y continúa probando con portales",
  "Prepárate para consecuencias imprevistas al aceptar ese trabajo peligroso bajo tierra",
  "Las ciudades bajo el mar albergan secretos terribles y sueños de grandeza",
  "Comandante el destino de la galaxia depende de tus decisiones morales cruciales",
  "Un meteorito de impacto reunirá materias y sueños protejamos nuestro planeta",
  "Sólido o líquido el sigilo es tu mayor arma contra caminantes patrullando",
  "La niebla devora la ciudad acompañada de sirenas que advierten horrores cercanos",
  "Destruye demonios con tu escopeta mientras un riff pesado retumba sin descanso",
  "El virus se propagó abre la puerta solo si confías totalmente en sobrevivientes",
  "Come todas las píldoras evita fantasmas hambrientos en laberintos infinitos de neón",
  "Gira piezas rápidamente para llenar líneas completas antes del inevitable bloqueo",
  "Libra combates multitudinarios lanzando personajes contra escenarios llenos de caos",
  "Un corazón conecta mundos Disney mientras compañeros luchan con llaves luminosas gigantes",
  "Hay un impostor entre nosotros completando tareas es tu única esperanza",
  "Alza tu espada ancestral desafiando a dioses olvidados en tierras destrozadas",
  "Las calles brillan con neón y ciberimplantes modifican cada susurro humano",
  "El miedo es el asesino de la mente recuerda tu mantra sobre la arena",
  "Esto pertenece en un museo aunque las trampas antiguas no quieran permitirlo",
  "Yippee ki yay celebra la navidad saltando desde rascacielos bajo fuego cruzado",
  "Tus misiones autodestructivas terminarán en cinco segundos si aceptas el desafío",
  "El agente con licencia para matar siempre prefiere su martini agitado sin hielo",
  "Venganza vestida de amarillo empuña la katana para ajustar cuentas sangrientas",
  "La esperanza es algo bueno quizá lo mejor y nunca muere en prisión",
  "Lo que hacemos en la vida resuena por toda la eternidad guerrero romano",
  "Esta es esparta grita mientras derribas al mensajero en la fosa",
  "Pueden quitarnos la vida pero jamás arrebatarán nuestra ansiada libertad",
  "Di hola a mi pequeño amigo antes de que todo explote a disparos",
  "Necesito velocidad sentir la adrenalina antes de volar sobre los cazas",
  "¿A quién vas a llamar cuando los fantasmas inunden la ciudad?",
  "Necesitarás un barco más grande para enfrentar lo que acecha bajo el agua",
  "Quedarse solo en casa significa preparar trampas geniales contra ladrones inútiles",
  "Pasamos juntos el desayuno y descubrimos que dentro somos todos bastante notables",
  "El miércoles todos visten rosa si quieres pertenecer al grupo ganador",
  "La vida se mueve rápido mejor tomas un descanso antes de perderla",
  "Aquí está Johnny anunciando terror tras una puerta destrozada a hachazos",
  "Un motel solitario puede esconder a un diablo con sonrisa maternal",
  "El silencio de los corderos viene con un Chianti y habas otoñales",
  "Siete pecados marcarán el final de un juego macabro con cajas",
  "La sospecha usual recae siempre en el individuo menos evidente del grupo",
  "Debes ir más profundo en el sueño para plantar una simple idea",
  "El amor traspasa agujeros negros y códigos Morse a través del tiempo",
  "Hasta la vista bebé dijo mientras congelaba su enemigo con nitrógeno líquido",
  "Furia en la carretera impulsa guerreros supervivientes por desolados páramos incendiados",
  "Vivir rápido y furioso significa familia primero acelerador después y frenos nunca",
  "John se tomó un mal día personal y nadie quedó en pie",
  "La grasa es el camino armonizando artes marciales con sabiduría empapada en tallarines",
  "Es tan esponjoso como para conquistar corazones con su risa villanesca",
  "Banana grita la tropa amarilla causando caos adorable con travesuras desmedidas",
  "La aventura comienza con globos llevándote a explorar cataratas perdidas y recuerdos",
  "Que comience el juego mientras una muñeca gigante observa cada movimiento",
  "El multiverso se rompió y ahora todos culpan al hechizo equivocado",
  "Una casa amarilla guarda rosquillas secretos y planes absurdos cada tarde",
  "El trono de hierro nunca fue cómodo para quienes buscaban dormir tranquilos",
  "La máscara verde transforma a cualquiera en caos con ritmo de mambo",
  "Un cuaderno oscuro demuestra que escribir nombres puede salir demasiado caro",
  "El niño elegido todavía necesita lentes limpios y buenos amigos cerca",
  "La señal del murciélago ilumina nubes cuando la ciudad pierde la calma",
  "Un paraguas volador convierte una niñera en leyenda sobre tejados londinenses",
  "La realidad falla cuando el conejo blanco vuelve a mirar su reloj",
  "El traje rojo entrega regalos pero también sabe pelear sobre azoteas",
  "Una guitarra encantada recuerda canciones familiares cruzando un puente de pétalos",
  "Los cazadores de mitos confirmaron que la explosión siempre mejora el episodio",
  "El chef diminuto dirige la cocina escondido bajo un gorro demasiado grande",
  "La cinta maldita espera siete días antes de arruinar cualquier pijamada"
],
  practiceLettersAndSymbols: [
  "a",
  "s",
  "d",
  "f",
  "g",
  "h",
  "j",
  "k",
  "l",
  ";",
  "q",
  "w",
  "e",
  "r",
  "t",
  "y",
  "u",
  "i",
  "o",
  "p",
  "!",
  "@",
  "#",
  "$",
  "%",
  "&",
  "*",
  "(",
  ")",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0"
],
  practiceWords: [
  "final",
  "sal",
  "luz",
  "oportunidad",
  "llave",
  "caminosción",
  "prebarquito",
  "mariposas",
  "prenegro",
  "téal",
  "flacoismo",
  "montañación",
  "despez",
  "resolción",
  "sueño",
  "preespejos",
  "hermanooso",
  "salción",
  "descamión",
  "camiónismo",
  "cuadernoción",
  "ojodad",
  "descubrido",
  "ojodad",
  "desguitarra",
  "ojo",
  "mar",
  "sal",
  "reflacoado",
  "alimentación",
  "imaginario",
  "ojo",
  "negroción",
  "osoismo",
  "subhoyismo",
  "sal",
  "superpandad",
  "repanado",
  "sal",
  "necesidades",
  "negromente",
  "inuniverso",
  "superpalabra",
  "aventuras",
  "subpuente",
  "guitarraado",
  "desvozdad",
  "perroción",
  "oportunidad",
  "desamigos",
  "luz",
  "prehermano",
  "solmente",
  "inperro",
  "rebarquito",
  "subamigosdad",
  "sol",
  "universoado",
  "cuadernoal",
  "soloso",
  "amigosdad",
  "palabra",
  "desbicicleta",
  "finción",
  "inperro",
  "reluzdad",
  "maral",
  "escalonesoso",
  "luzal",
  "ventana",
  "marar",
  "pezar",
  "rey",
  "puenteado",
  "día",
  "perroado",
  "montaña",
  "subsalmente",
  "renaturaleza",
  "escalonesoso",
  "superosoar",
  "naturaleza",
  "desmuralla",
  "perroar",
  "reuniversoar",
  "subsaloso",
  "universoismo",
  "hoy",
  "montañamente",
  "espejosción",
  "remurallaal",
  "desdía",
  "aventuras",
  "pan",
  "intémente",
  "reventanaoso",
  "verdear",
  "supervoz",
  "inguitarra",
  "hoy",
  "bicicletaado",
  "nieve",
  "reté",
  "submar",
  "llave",
  "cuaderno",
  "preojoismo",
  "mar",
  "esperanzadad",
  "espejosción",
  "caminos",
  "barquitodad",
  "subsueñoal",
  "pez",
  "inhermano",
  "reluzoso",
  "oso",
  "inllave",
  "mariposas",
  "dessal",
  "superojoado",
  "muralla",
  "ojo",
  "oso",
  "sueñoado",
  "oportunidad",
  "osoar",
  "montaña",
  "solal",
  "guitarraar",
  "cuadernoado",
  "subfinoso",
  "subvozismo",
  "prellaveoso",
  "llave",
  "recamiónado",
  "inespejos",
  "inesperanza",
  "sueño",
  "muralla",
  "conocimiento",
  "puente",
  "superreydad",
  "necesidades",
  "sueño",
  "puente",
  "amigosción",
  "negro",
  "subsolmente",
  "indescubrido",
  "responsable",
  "puente",
  "hermano",
  "inbicicleta",
  "subté",
  "oso",
  "subdíaismo",
  "bicicleta",
  "amigosción",
  "inluzoso",
  "téar",
  "desmuralla",
  "superpezismo",
  "desreyismo",
  "insol",
  "puenteal",
  "prenegro",
  "palabración",
  "espejosar",
  "preojo",
  "repan",
  "voz",
  "subsoloso",
  "prehoy",
  "puenteismo",
  "desverdeoso",
  "rey",
  "mariposasdad",
  "día",
  "escalones",
  "hermano",
  "gato",
  "día",
  "inverdeismo",
  "universoal",
  "revozar",
  "preguitarra",
  "rereyción",
  "duende",
  "universoado",
  "supernieve",
  "camión",
  "hermanooso",
  "pregato",
  "mar",
  "bicicleta",
  "alimentación",
  "gato",
  "subverdeado",
  "pez",
  "espejos",
  "té",
  "desflaco",
  "prebicicleta",
  "pez",
  "precuaderno",
  "hoy",
  "subdíaado",
  "maral",
  "inespejosar",
  "ventana",
  "sol",
  "universoal",
  "naturaleza",
  "escalones",
  "necesidades",
  "subduende",
  "subsal",
  "renieve",
  "subflacoismo",
  "cuaderno",
  "precaminos",
  "espejosdad",
  "negro",
  "descubrido",
  "desmontaña",
  "díaoso",
  "remontañaal",
  "gato",
  "electricidad",
  "caminos",
  "reventana",
  "rey",
  "subduende",
  "resalismo",
  "inaventuras",
  "desvozmente",
  "tranquilidad",
  "subverde",
  "inamigos",
  "hermanomente",
  "descubrido",
  "necesidades",
  "incaminososo",
  "descubrido",
  "aventuras",
  "ventana",
  "amigosción",
  "descubrido",
  "palabra",
  "barquitodad",
  "negroar",
  "negro",
  "aventuras",
  "alimentación",
  "vozdad",
  "salmente",
  "bicicleta",
  "verde",
  "innieve",
  "guitarra",
  "sol",
  "superojoismo",
  "llave",
  "escalones",
  "pez",
  "aventuras",
  "día",
  "renegro",
  "inflacoal",
  "voz",
  "sol",
  "subsol",
  "gato",
  "presal",
  "duendeismo",
  "tranquilidad",
  "innievedad",
  "puentear",
  "espejosdad",
  "personalidad",
  "subventana",
  "subguitarra",
  "fin",
  "téado",
  "desmaral",
  "barquitoismo",
  "guitarradad",
  "montañaar",
  "pretéado",
  "reflaco",
  "inpalabra",
  "reespejos",
  "tranquilidad",
  "nieve",
  "inamigosción",
  "intédad",
  "pez",
  "verde",
  "preflaco",
  "luzmente",
  "rebarquito",
  "verdeismo",
  "camióndad",
  "solismo",
  "superverde",
  "rehermano",
  "perroal",
  "reuniversoar",
  "pan",
  "deshoyismo",
  "revozal",
  "aventuras",
  "nievedad",
  "subllave",
  "díamente",
  "universo",
  "inllave",
  "prevoz",
  "muralla",
  "amigos",
  "desbicicleta",
  "resueñooso",
  "nieve",
  "esperanzaado",
  "espejosado",
  "caminosado",
  "gatodad",
  "murallaado",
  "reuniverso",
  "verde",
  "pez",
  "inpan",
  "subsol",
  "negro",
  "subduendedad",
  "palabra",
  "sueño",
  "esperanza",
  "puente",
  "duende",
  "barquitoción",
  "hermanomente",
  "bicicleta",
  "recamión",
  "negroar",
  "sueñoción",
  "subperrodad",
  "oso",
  "flaco",
  "ojo",
  "verde",
  "personalidad",
  "prepuenteoso",
  "sal",
  "pezar",
  "vozal",
  "descamióndad",
  "guitarraado",
  "guitarra",
  "osoal",
  "tranquilidad",
  "hoy",
  "duendeción",
  "esperanzadad",
  "insueño",
  "inventana",
  "palabra",
  "escalones",
  "camión",
  "fin",
  "mar",
  "necesidades",
  "amigos",
  "subojoción",
  "inpalabra",
  "preamigos",
  "fin",
  "gatoción",
  "alimentación",
  "esperanzaar",
  "incaminos",
  "electricidad",
  "inpezismo",
  "cuadernoal",
  "pez",
  "reyal",
  "desosomente",
  "mariposas",
  "subluz",
  "fin",
  "fin",
  "caminos",
  "bicicletaado",
  "fin",
  "desguitarra",
  "sal",
  "caminososo",
  "oportunidad",
  "día",
  "luzismo",
  "hermano",
  "guitarra",
  "imaginario",
  "necesidades",
  "resueño",
  "barquito",
  "fin",
  "presueño",
  "prefinoso",
  "recuaderno",
  "rebarquitoar",
  "desnieveismo",
  "flaco",
  "pez",
  "soldad",
  "desluzismo",
  "desuniverso",
  "nieveoso",
  "electricidad",
  "montaña",
  "guitarra",
  "universo",
  "montaña",
  "desbarquito",
  "voz",
  "preventana",
  "panal",
  "montaña",
  "oportunidad",
  "ojooso",
  "luz",
  "negro",
  "supermuralla",
  "mariposas",
  "hoy",
  "mariposas",
  "desmuralla",
  "sol",
  "descubrido",
  "gatoado",
  "oportunidad",
  "téoso",
  "perro",
  "sal",
  "inpan",
  "llaveción",
  "esperanzaar",
  "murallaar",
  "verde",
  "gato",
  "supermar",
  "oportunidad",
  "preté",
  "cuadernoado",
  "universo",
  "ventana",
  "imaginario",
  "inojoado",
  "esperanzaoso",
  "tranquilidad",
  "perro",
  "pezar",
  "aventuras",
  "pezoso",
  "imaginario",
  "despez",
  "pregato",
  "responsable",
  "puente",
  "puente",
  "reyal",
  "negro",
  "incaminosal",
  "barquitoismo",
  "aventuras",
  "saloso",
  "camión",
  "vozción",
  "desespejosar",
  "incamiónismo",
  "renieve",
  "sol",
  "preduendedad",
  "duendeción",
  "esperanza",
  "preescalones",
  "muralla",
  "fin",
  "despan",
  "desfinmente",
  "verde",
  "solar",
  "pez",
  "barquito",
  "naturalezaal",
  "cuadernooso",
  "supersaldad",
  "pez",
  "subluz"
],
  practiceScrollParagraphs: [
  "En una galaxia donde las cantinas nunca cierran, un piloto con chaqueta prestada intenta convencer a su copiloto peludo de que el hiperespacio también sirve para llegar temprano a una reunión familiar. Afuera, los soles gemelos pintan el hangar de dorado, y adentro alguien jura que esta vez el plan no depende de improvisar con cables, sarcasmo y una puerta que se abre solo cuando nadie la mira.",
  "La noche cae sobre una ciudad de neones y lluvia, mientras una motocicleta roja atraviesa avenidas llenas de anuncios que prometen futuros imposibles. En la pantalla gigante, una cantante virtual repite un estribillo que todos conocen, y un grupo de amigos decide que salvar el barrio empieza por hackear una máquina expendedora que solo acepta monedas de otra dimensión.",
  "En el sótano de una casa suburbana, cuatro bicicletas descansan contra la pared junto a mochilas llenas de linternas, dados y chocolates derretidos. El mapa dibujado a mano dice que el portal está debajo de la cancha de baloncesto, pero nadie sabe si la criatura del otro lado teme más a la luz, a la música ochentera o a una buena amistad que se niega a rendirse.",
  "El museo estaba cerrado, pero las estatuas ya discutían como cada medianoche. Un faraón preguntaba por el control remoto, un vaquero defendía su caballo miniatura, y una científica con gafas enormes tomaba notas sobre el comportamiento de un tiranosaurio que solo quería jugar a buscar huesos. El guardia nuevo entendió demasiado tarde que su turno sería cualquier cosa menos tranquilo.",
  "Sobre un tejado húmedo, un héroe con máscara ajusta sus lanzadores mientras escucha por radio que el tráfico está detenido por un robot con complejo teatral. Abajo, la gente levanta celulares para grabar, pero el verdadero reto no es esquivar rayos láser: es entregar una pizza antes de que se enfríe y llegar a clase sin revelar por qué trae telarañas en la mochila.",
  "La escuela de magia había organizado un torneo de cocina, lo cual parecía seguro hasta que alguien confundió levadura con polvo flotador. Las calderas empezaron a cantar, los pasteles escaparon por las ventanas y un sombrero antiguo declaró que el mejor plato era la valentía. En medio del caos, una estudiante descubrió que el hechizo más útil era leer bien las instrucciones.",
  "En una isla custodiada por dinosaurios, el sistema de seguridad volvió a fallar justo cuando el guía prometía que todo estaba bajo control. Los visitantes miraron el vaso de agua temblar, escucharon un rugido demasiado cercano y comprendieron que ningún folleto turístico menciona la parte en la que debes negociar con velocirraptores usando una bengala, un jeep y mucha suerte.",
  "El detective más famoso de la televisión local llevaba gabardina, libreta y una taza de café que nunca se vaciaba. Su caso parecía simple: encontrar quién había robado el último cartucho de la consola retro. Pero cada pista lo llevaba a otro nivel, desde el salón arcade hasta una guarida secreta donde los villanos discutían estrategias como si estuvieran en una partida cooperativa.",
  "En el reino de los bloques, un constructor despertó con la misión de levantar una torre antes del anochecer. Tenía madera, piedra, antorchas y una paciencia que se agotaba cada vez que escuchaba un siseo detrás de la pared. Aun así, siguió picando bajo la luna cuadrada, convencido de que todo gran castillo empieza con una mesa de crafteo y una idea terca.",
  "La nave de exploración recibió una señal antigua desde un planeta cubierto por junglas azules. La capitana pidió cautela, el androide pidió datos, y el cocinero preguntó si había forma de preparar sopa con flores bioluminiscentes. Cuando aterrizaron, descubrieron ruinas que respondían a canciones pop, como si una civilización perdida hubiera guardado su historia en el coro perfecto.",
  "En una competencia mundial de monstruos de bolsillo, la final no se decidió por fuerza bruta sino por confianza. El entrenador recordó cada caminata bajo la lluvia, cada centro de curación a medianoche y cada derrota que enseñó algo útil. Cuando su compañero saltó al campo, las luces del estadio parecieron encenderse solo para ese momento compartido entre paciencia, estrategia y amistad.",
  "El fontanero del reino champiñón había prometido tomarse vacaciones, pero una tubería verde apareció en mitad del hotel y arruinó el plan. Del otro lado había castillos flotantes, caparazones veloces y una princesa que ya tenía lista una lista de tareas. El viaje sería peligroso, aunque nadie podía negar que saltar sobre problemas seguía siendo una forma bastante directa de resolverlos.",
  "La banda ensayaba en un garaje decorado con pósters de robots gigantes, guitarras viejas y una espada de plástico que todos trataban con respeto ceremonial. Querían escribir la canción definitiva para derrotar al jefe final de la adolescencia, ese enemigo invisible hecho de exámenes, mensajes sin responder y ganas de descubrir quién eres antes de que termine el verano.",
  "En una ciudad donde los fantasmas pagan alquiler y los cazadores llevan mochilas nucleares, una llamada nocturna reportó actividad paranormal en una biblioteca pública. Los libros flotaban, los archivadores susurraban spoilers y una entidad verde se había comido todas las tarjetas de préstamo. El equipo llegó con trampas, bromas malas y la certeza de que ningún silencio dura mucho cuando alguien grita.",
  "El último nivel del torneo arcade tenía fama de imposible. Las luces parpadeaban, la máquina zumbaba como nave espacial y el protagonista en la pantalla parecía conocer todos los trucos del jugador. Con una moneda final y las manos temblando, alguien descubrió que ganar no siempre significa romper el récord: a veces significa que todo el local empieza a corear tu nombre."
],
} as const;
